spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    consumer:
      group-id: test-consumer-group

topics:
  vehicle-input-topic-name: vehicle-input-topic
  vehicle-output-topic-name: vehicle-output-topic
  partitions: 3
  replicationFactor: 2
  consumersNumber: 3

