spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    consumer:
      group-id: test-consumer-group
      properties:
        isolation.level: read_committed
    producer:
      transaction-id-prefix: tx-

topics:
  vehicle-input-topic-name: vehicle-input-topic
  vehicle-output-topic-name: vehicle-output-topic
  partitions: 3
  replicationFactor: 2
  consumersNumber: 3

# uncomment to monitor transactions in logs
#
#logging:
#  level:
#    org.springframework.transaction: trace
#    org.springframework.kafka.transaction: debug